### ISSUE TITLE
Shouldn't have to check credentials every time

### ISSUE THREAD

**Issue by muschellij2** [adigherman/nitrcbot#2]
For IXI data set, which is public, I can run:

```r
ixi_project <- read_nitrc_project('ixi')
```
But I get a lot of `Invalid NITRC credentials!`, which is understandable but not accurate for `ixi`.  

If I grab some scanning parameters without signing in (which should work without login):
```
x = get_scan_params("NITRC_IR_E10452")
```
I get an error, but if I ruN:

```r
session_ID = "NITRC_IR_E10452"
        scan_params <- content(GET(paste0("https://www.nitrc.org/ir/data/experiments/", 
            session_ID, "/scans?xsiType=xnat:mrScanData&columns=xnat:imageScanData/ID,xnat:mrScanData/parameters/frames,xnat:mrScanData/parameters/te,xnat:mrScanData/parameters/tr,xnat:mrScanData/parameters/flip,xnat:mrScanData/parameters/voxelRes/x,xnat:mrScanData/parameters/voxelRes/y,xnat:mrScanData/parameters/voxelRes/z,xnat:mrScanData/fieldStrength,xnat:mrScanData/parameters/matrix/x,xnat:mrScanData/parameters/matrix/y,xnat:mrScanData/parameters/partitions,xnat:mrScanData/quality&project=kin&format=json")))
```
I get relevant data back.  

@kalinn

**Comment by adigherman** [comment]
This should be fixed. Let me know otherwise. Thanks!

Sent from my iPhone

On Feb 14, 2018, at 3:44 PM, John Muschelli <notifications@github.com<mailto:notifications@github.com>> wrote:


For IXI data set, which is public, I can run:

ixi_project <- read_nitrc_project('ixi')

But I get a lot of Invalid NITRC credentials!, which is understandable but not accurate for ixi.

If I grab some scanning parameters without signing in (which should work without login):

x = get_scan_params("NITRC_IR_E10452")


I get an error, but if I ruN:

session_ID = "NITRC_IR_E10452"
        scan_params <- content(GET(paste0("https://www.nitrc.org/ir/data/experiments/",
            session_ID, "/scans?xsiType=xnat:mrScanData&columns=xnat:imageScanData/ID,xnat:mrScanData/parameters/frames,xnat:mrScanData/parameters/te,xnat:mrScanData/parameters/tr,xnat:mrScanData/parameters/flip,xnat:mrScanData/parameters/voxelRes/x,xnat:mrScanData/parameters/voxelRes/y,xnat:mrScanData/parameters/voxelRes/z,xnat:mrScanData/fieldStrength,xnat:mrScanData/parameters/matrix/x,xnat:mrScanData/parameters/matrix/y,xnat:mrScanData/parameters/partitions,xnat:mrScanData/quality&project=kin&format=json")))

I get relevant data back.

@kalinn<https://github.com/kalinn>
